# Generated by Django 6.0.4 on 2026-04-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_level', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('playing', 'Playing'), ('win', 'Win'), ('lose', 'Lose')], default='playing', max_length=20)),
                ('sanity_remaining', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
